# Generated by Django 6.0.7 on 2026-07-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('membership_type', models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SportsClub',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=100)),
                ('coach_name', models.CharField(max_length=100)),
                ('max_capacity_students', models.IntegerField()),
            ],
        ),
    ]
