# Generated by Django 6.0.7 on 2026-07-29 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
